### ISSUE TITLE
tracking initial author

### ISSUE THREAD

**Issue by ujwal-setlur** [labs42io/circleci-monorepo#23]
Thank you for your script. I adapted it to work with the [rush](https://rushjs.io) monorepo manager.

I know this is not not an issue with the script per se, but right now, any secondary workflows that are triggered are using the ``CIRCLE_USER_TOKEN`` token which may not belong to the author of the original commit.

Any ideas on how to keep track of the original author?

**Comment by ujwal-setlur** [comment]
Of course, I could keep a list of all known user tokens and do a lookup based on the author of the original commit...but that doesn't scale... :)

**Comment by dimadeveatii** [comment]
This is how we did it in other projects, and I agree, it's not the best solution as you should always keep it in sync with your team. For each new team member, you have to ask them to generate a token and configure that token so that it is handled by the script.  

As CircleCI doesn't allow to trigger workflows in the name of other users, I don't think there is a better solution.

**Comment by ujwal-setlur** [comment]
Yeah, that’s how I ended up doing it, and it works.
